### ISSUE TITLE
Python CLI is GA ready using release checklist

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#110]
**Feature Overview & Customer Need**
We need to make sure the CLI is GA ready with all aspects related like
License
Notices
Final test on help and docs
and so on
Let's place all GA related tasks under this Epic and edit the DOD

**DOD**
- [x] Release process documentation is ready
- [x] Release artifacts should zip or tar for each OS type
- [x] Test plan for release is ready
- [x] Security review was done and issues were raised
- [x] License is according to Legal instructions
- [x] Notices file is added 
- [x] Final tests on help and docs
- [x] Status should be changed to GA [here] (https://github.com/cyberark/conjur-api-python3#status-alpha) or erased? @izgeri  WDYT?
- [x] CLI should be release as GA

**Comment by sigalsax** [comment]
@InbalZilberman what is the diff between this and [this](https://app.zenhub.com/workspaces/palmtree-5d99d900491c060001c85cba/issues/cyberark/conjur-api-python3/82)? the names are basically the same

**Comment by izgeri** [comment]
For now, the project should be clear that it contains two components:
- The self-contained Conjur command-line tool (`conjur`) -- `Certified`
- Python3-based SDK for Conjur -- `Community`

It is up to you @sigalsax and @InbalZilberman how you want to make this clear, but please aim to make this clear in the top of the README when you're preparing to release this project. If you want to use our certification level badges or standard text, you can see the boilerplate language here: https://github.com/cyberark/conjur-template/blob/main/README.md. Please at least link to the [certification level definitions](https://github.com/cyberark/community/blob/master/Conjur/conventions/certification-levels.md) in what you write.

**Comment by sigalsax** [comment]
@izgeri 
Adding this like so:

```
## Certificate level

### CLI
{certified badge}

### SDK
{community badge}
 
```

**Comment by izgeri** [comment]
@sigalsax this looks good to me. Thank you!

**Comment by InbalZilberman** [comment]
@sigalsax LGTM also, thanks!

**Comment by sigalsax** [comment]
@InbalZilberman can we close this?

**Comment by sigalsax** [comment]
closing as we have finished :)
