### ISSUE TITLE
CLI login logout commands

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#119]
## **Feature Overview & Customer Need**

**As a**  Conjur user 
**I would like to** use the conjur cli 
**In order to** login and logout of Conjur

login    - Logs in and caches credentials so that the users details are kept throughout his work.

logout    - Logs out

Basically these are the commands

conjur [global options]  **login** -u  user or host name  -p password

conjur [global options]  **logout**

Right now authenticate is **out of scope**

## User Experience

Use these links to the help mockup:

Login:  https://ljfz3b.axshare.com/#id=wy4eju&p=conjur_help__login&c=1

Logout: https://ljfz3b.axshare.com/#id=j2pl87&p=conjur_help__logout&c=1

### Login

Login can run without any arguments or flags at all and then the username and password is prompt to the user, like so:
conjur login
> Enter your login name to log into Conjur: admin
> Please enter your login password or API key (this will not be echoed): 
Successfully logged in to Conjur!

After a successful login we save the logged in user so it will continue on the next actions with these credentials. If we do save it in a cache/file we need to notify the user of it. This feature assumes that we save it in a cache, R&D should challenge that.

When executing the command with the login-name (e.g., bob), the user will be prompted to enter a password/API key, like so:
conjur login -u bob
> Please enter bob’s password or API key (this will not be echoed): 
Successfully logged in to Conjur!

When the user enters wrong credentials, or the .netrc file is missing/corrupted, the response would be according to template - 
Failed to -action on something-.  -Reason- (Error: code)  suggestion to fix the problem  

Failed to list. Unable to authenticate with Conjur (Error: 401). Please check your credentials and log in again.

When the user is not logged in and tries to run a command, like “list”, he is directly promoted to log in to Conjur, like so:
 Failed to login. Unable to authenticate with Conjur (Error: 401). Please log in and try again.
Do not state the creation of .netrc

### Logout
conjur logout
Assumption a cache is found with user credentials.

We would like to improve the UX of logout message for successful "Logged out from Conjur"

Making sure that the user is aware if the logout scenarios and we are able to distinguish between
1. If it is the first logout attempt (netrc is not empty), then the message: “Successfully logged out from Conjur” is a good one.
2. The next attempts to log out should output different message, like: “You are already logged out”.
3. If the netrc is deleted, trying to logout would output: “Successfully logged out from Conjur” (today in Ruby there’s no error.. see below).
4. If the netrc has no write permissions, trying to logout would output: “Failed to log out. (error: permission denied).”

Messages should be reviewed by PO, TW

## Quality

Make sure we have test coverage of the policy commands.  Create test plan and execute accordingly.

## Process logic and Demo

**Demo flow 1**
Conjur use with a machine that the Python CLI already been installed and conjur init run

`conjur login -u alice`

the user is prompt with

`Please enter alice's password (it will not be echoed):`

`Successfully logged in to Conjur!`

`conjur logout`

The user sees the following message

`Logged out from Conjur`

**Demo flow 2**
Demo same scenario without user name.
`conjur login`
**Demo flow 3**
Demo same scenario with user name and password or api key as argument
`conjur login -u alice -p $ENV_VAR`
**Demo flow 4**
Conjur use with a machine that the Python CLI already been installed and conjur init run
then run
`conjur logout`
The user sees the following message

`Failed to log out. Log in first.`

## User messages

All user messages regarding policy actions should be reviewed again

Especially error messages 
if an argument is missing we need to return the help of the command 

## Documentation

Please provide enhance documentation in online help and readme

## DOD

- [x] Implement the login logout commands Conjur Python CLI in all 3 platforms
- [x] ADDRESS the port issue. We should allow all ports and should be configurable.
- [x] Demo the flow described above
- [x] Automatic integration tests written according to a test plan and passed successfully
- [x] Fill in the user messages - link to a page with all user messages for CLI saved and reviewed. 
- [x] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed.  (see below comment)
- [x] Logs were reviewed by TW and PO
- [ ] Are there new Audits to this feature? If so please document them and provide here a link (N/A)

**Comment by sigalsax** [comment]
- [x] Implement the login logout commands Conjur Python CLI in all 3 platforms
- [x] ADDRESS the port issue. We should allow all ports and should be configurable.
- [ ] Demo the flow described above **(DONE during our meetings)**
- [x] Automatic integration tests written according to a test plan and passed successfully
- [ ] UT written for all classes\functions\major logic flows and passed successfully **(N/A after main functionality implementation)**
- [x] Security review has been performed **Scan was performed. See [here](https://conjurhq.slack.com/archives/C01CMPFHZS6/p1609836931278100)**
- [ ] Security action items were taken **Sasha opened a [ticket](https://conjurhq.slack.com/archives/C01CMPFHZS6/p1609072397110600?thread_ts=1607501862.286800&cid=C01CMPFHZS6)**
- [ ] Supportability was taken into account - troubleshooting section in the readme enhanced and reviewed by TW & PO **N/A will be done during docs stage**
- [x] Fill in the user messages - link to a page with all user messages for CLI saved and reviewed. **See [here](https://github.com/cyberark/conjur-docs/issues/1310)**
- [x] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed. **See [here](https://github.com/cyberark/conjur-docs/issues/1310)**
- [x] Logs were reviewed by TW and PO 
- [ ] Are there new Audits to this feature? If so please document them and provide here a link **N/A**
- [ ] Configurations were reviewed by PO - link if something changed **N/A**
- [ ] Documentation HO to TW **N/A will be done during docs stage**

**Comment by sigalsax** [comment]
closing epic as all tests passed and logic has been implemented! yay!
