### ISSUE TITLE
Host-Factory new CLI command

### ISSUE THREAD

**Issue by szamir1** [cyberark/conjur-api-python3#285]
# Feature Overview & Customer Need
As a Conjur user
I would like to use the Conjur cli
In order to automatically creates hosts and enrolls them into one or more layers. 

A new command will be called host-factory
We will use sub command

host-factory - creates a host-factory service that will be used to create hosts
The commands will be used as follow:

conjur host-factory
<- returns a list in the same structure list command will

Args description:
-i --id - provide the resource identifier
-p --privilege - provide privilege name

Expected behavior should not change from the corresponding command in Ruby CLI
@sharonr78 should provide the right help screen
Help is according to https://ljfz3b.axshare.com/#id=s9nycf&p=conjur_help__policy&g=1

### Process logic and requirements 
Conjur user with a machine that the Python CLI already been installed and conjur init & login run against a Conjur/ Conjur Enterprise machine with the following resources:

MyAccount:group:conjur-root-admins

conjur resource list-roles - i MyAccount:group:conjur-root-admins -p read
[
"MyAccount:user:admin"
]

If the user enters a non-existing privileged role, we need to return the help of the command
For example:
conjur resource list-roles -i MyAccount:group:conjur-root-admins -p delete

### Demo
Demo each option that was implemented
Show that the resources has permitted_roles correct

Delete a resource by using !delete in a policy
Show that the option of running permitted_roles is failing.

### User messages
All user messages regarding resource actions should be reviewed

### Especially error messages
if an argument is missing we need to return the help of the command

### Quality
- Make sure we have test coverage of the host-factory command.
- Create test plan and execute accordingly.

### Documentation
Please provide enhance documentation in online help and readme

### DOD
- [ ] Implement the resource's commands Conjur Python CLI in all 3 platforms
- [ ]  Demo the flow described above
- [ ]  Automatic integration tests written according to a test plan and passed successfully
- [ ]  Fill in the user messages - link to a page with all user messages for CLI saved and reviewed.
- [ ]  Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed.
- [ ]  Logs were reviewed by TW and PO
- [ ]  Are there new Audits to this feature? If so please document them and provide here a link (N/A)

**Comment by InbalZilberman** [comment]
duplicate
