### ISSUE TITLE
Automation - Add certificate flows to pipeline

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur-api-python3#294]
In the CLI we need to check against two different certificate flows, when the server is configured with:
1. a verifiable ca-signed certificate (this task)
2. a non-verifiable ca-signed certificate (current)

### General Information

Python comes with a list of trusted CAs. Every certificate signed by those CAs will be considered as trusted certificate. Those CAs are located in a file called cacerts.pem. To get the path of this file, run in python3 -c "import certifi; print(certifi.where())". To make a certificate verifiable we need to add the root CA to that location!

### Task
At a high level, we want to add the a verifiable ca-signed certificate to our test pipeline
- [ ] Automate the steps mentioned in this [doc](https://github.com/cyberark/conjur-api-python3/blob/master/docs/Setting_3rd_party_cert_environment.md) to create CA and generate CA-signed certificate
- [ ] Build the test binary artifact as described under the section _Running tests with configurable environment_ [here](https://github.com/cyberark/conjur-api-python3/pull/284/files) to allow the certificate to be verifiable
- [ ] Run the binary that will trigger the tests to run with a verifiable ca signed cert
