### ISSUE TITLE
Rename only Python SDK and CLI

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#296]
### Feature Overview & Customer Need
Name Change - to be delivered in 12.2
Includes 2 things:

1. Documentation - Done by TW @shulifink and PM @boazmichaely without team involvement
2. Artifacts according to priority defined in the Epic card
Our artifacts for this scope
- CLI (Python) and Python SDK
We need to change the following areas:
![Screen Shot 2021-05-12 at 9.01.52.png](https://images.zenhubusercontent.com/5ce1b1cd1285ef7423fe0582/c6d2fb0b-c1e1-436f-81e1-065606bf785b)

Rename rules are:

![Screen Shot 2021-05-12 at 10.14.45.png](https://images.zenhubusercontent.com/5ce1b1cd1285ef7423fe0582/0571c407-e18b-4cfe-b994-f3d9cf509063)

### DOD
- [x] Implement the rename according to guidelines for CLI (Python) and Python SDK
- [x] If there are user facing commands, logs that are changed and are affecting current documentation we need to create doc tickets for them.
- [x] Demo the rename results according to requirements/flows to team and PO - PLEASE record it
