### ISSUE TITLE
Python CLI Deployment

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#78]
**Feature Overview & Customer Need**
**As a**  Conjur user 
**I would like to** install and run my Conjur CLI in my local machine
**In order to** perform the actions I like most in Conjur and operate it

**As a**  Conjur user 
**I would like to** be able to install from my CD pipeline
**In order to** run Conjur CLI in my pipeline and tests if needed

Conjur Python CLI to be on deployed on VMs or local computers of our users.
The platforms the CLI needs to support are:
- RHEL 7 , 8
- Windows 10
- Mac

The deployment of the should be 
1. Manual 
2. Using a single executable file. Recommended - be the same UX for each platform.
3. The name of the CLI when running it should be "python-conjur-cli" or better yet conjur

**Process Logic & Demo flow**
Conjur user goes to release site of the Python CLI and download the CLI file
Conjur user is running the cli for example:

`conjur --help`
The current response is OK.

The Conjur user can see what version of the cli s/he is using by running
`conjur -v or conjur --version`
conjur cli version 6.0.0

see mocks for more details on the response: https://ljfz3b.axshare.com/#id=yokln4&p=conjur_main_help&g=1

**Support**
If any prerequisite is not met while running the cli a proper message should be given to the user.

**Documentation**
Please provide enhance documentation in online help and readme

**Open issue**
Do we need to sign this single executable? find out with PM
h2. DOD
- [x] Implement an easy way to deploy Conjur Python CLI in all 3 platforms
- [x] Implement the command version as described here ^ 
- [x] Implement the command help according to look and feel of Ruby CLI
- [x] Demo the flow described above
- [ ] Automatic integration tests written according to a test plan and passed successfully
- [x] UT written for all classes\functions\major logic flows and passed successfully
- [ ] Security action items were taken
- [x] Supportability was taken into account - troubleshooting section in the readme enhanced and reviewed by TW & PO
- [ ] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed. 
- [ ] Logs were reviewed by TW and PO
- [x] Are there new Audits to this feature? If so please document them and provide here a link
- [x] Configurations were reviewed by PO - link if something changed
- [x] Documentation HO to TW and review docs

**Comment by sharonr78** [comment]
Hi @InbalZilberman, following the Legal issue we addressed to RavitalS on Nov 26, we are required to display the CyberArk copyright in our CLI.
The copyright can be part of the version command, when executing `conjur --version` like so:
```
conjur --version

Conjur Python CLI version x.x.x
Copyright © 2020 CyberArk Software Ltd. All rights reserved.
<www.cyberark.com>
```

**Comment by sigalsax** [comment]
-  Automatic integration tests written according to a test plan and passed successfully
-  Security action items were taken
-  Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed.
-  Logs were reviewed by TW and PO

Are N/A because of the following:
1. We will run manual tests and provide a list of tests that we will run
2. Security actions should be provide level and not per small feature (unless we are talking about init/authn/host/user because there we deal with sensitive data)
3. We don't provide any logs here because this epic just deals with help screens and installation. In other words the user hasn't run any command to see any logs
