### ISSUE TITLE
Variable Commands - improve quality and documentation

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#80]
## **Feature Overview & Customer Need**

**As a**  Conjur user 
**I would like to** use the conjur cli 
**In order to** perform actions on variables defined in Conjur:

1. Read variable's value
2. Read multiple variables values
3. Write variable value

The variable command help will look as follows
NAME

  variable - Manage variables

SYNOPSIS

conjur variable  get -i <variable_id1> <variable_id2> <variable_id3> 

conjur variable  set -i <variable_id> -v <variable new value>

COMMANDS

 {get, set}

  get    Get the value of a variable can be applied to get the value of several variables

  set    Set the value of a variable

optional arguments:

 -h, --help show this help message and exit

final help is located here: https://ljfz3b.axshare.com/#id=gxnkww&p=conjur_help__variable&g=1 

## Quality

Make sure we have test coverage of the variable commands. Create test plan and execute accordingly.

## Process logic and Demo

Conjur use with a machine that the Python CLI already been installed and conjur init run

The user is able to see a variable value

The user is able to set the variable value

The user is able to see several variable values

All variable ids with spaces should be wrapped with `"`. For example `conjur variable get "secrets/spaces with spaces" secrets/nospaces`

## User messages

All user messages regarding variable should be reviewed again

Especially error messages 

If an argument is missing we need to return the help of the command 

## **Documentation**

Please provide enhance documentation in online help and readme.

## DOD

- [x] Implement the variable commands Conjur Python CLI in all 3 platforms
- [ ] Demo the flow described above
- [x] Automatic integration tests written according to a test plan and passed successfully
- [x] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed. 
- [x] Logs were reviewed by TW and PO
- [x] Fill in the user messages - link to a page with all user messages for CLI saved and reviewed. 
- [ ] Are there new Audits to this feature? If so please document them and provide here a link (N/A)

**Comment by InbalZilberman** [comment]
design https://github.com/cyberark/conjur-api-python3/blob/master/design/variable_command_design.md
