### ISSUE TITLE
List command enhancements 

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur-api-python3#81]
## **Feature Overview & Customer Need**

**As a**  Conjur user 
**I would like to** use the conjur cli 
**In order to** understand what resources were defined in my Conjur

The list command help will look as follows

NAME

  list - Lists all available resources beloging to this account

SYNOPSIS

  conjur [global options] list [command options] 

COMMAND OPTIONS

  --[no-]inspect       - Show full object information

  -k, --kind=arg       - Filter by kind (default: none)

  -l, --limit=arg      - Maximum number of records to return (default: none)

  ~~-o, --offset=arg      - Offset to start from (default: none)~~ _(not implemented in Ruby)_

  ~~-r, --[no-]raw-annotations - Show annotations in 'raw' format~~

  --role=ROLE        - Role to act as. By default, the current logged-in role is used. (default: none)

  -s, --search=arg      - Full-text search on resource id and annotation values (default: none)

We need to implement these options according to prioritisation: --inspect, kind, search, limit, offset and role

Please provide effort estimation for each one before implementation.

UX should be the same as in Ruby CLI today
Final help is here: https://ljfz3b.axshare.com/#id=obmn4b&p=conjur_help__list&g=1

## Quality

Make sure we have test coverage of the variable commands.  Create test plan and execute accordingly.

## Process logic and Demo

Conjur use with a machine that the Python CLI already been installed and conjur init run

`conjur list`      

result can with

[

 "cucumber:policy:root",

 "cucumber:policy:conjur/authn-azure/test",

 "cucumber:webservice:conjur/authn-azure/test",

 "cucumber:webservice:conjur/authn-azure/test/status",

 "cucumber:variable:conjur/authn-azure/test/provider-uri",

 "cucumber:group:conjur/authn-azure/test/apps",

 "cucumber:group:conjur/authn-azure/test/operators",

 "cucumber:user:authn-azure-test-operator",

 "cucumber:user:bob",

 "cucumber:host:azurehost",

 "cucumber:host:needApiKey",

 "cucumber:host:azureNgcpNapikeyhost"

]

Demo each option that was implemented

## User messages

All user messages regarding list should be reviewed again

Especially error messages 

if an argument is missing we need to return the help of the command 

## **Documentation**

Please provide enhance documentation in online help and readme

## DOD

- [ ] Implement the list command Conjur Python CLI in all 3 platforms
- [ ] Demo the flow described above
- [ ] Automatic integration tests written according to a test plan and passed successfully
- [ ] Fill in the user messages - link to a page with all user messages for CLI saved and reviewed. 
- [ ] Fill in the logs and place here a link to the logs files - link to a page with all logs for CLI saved and reviewed. 
- [ ] Logs were reviewed by TW and PO
- [ ] Are there new Audits to this feature? If so please document them and provide here a link (N/A)
